---
- name: oVirt image template
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    # Contains encrypted `engine_password` varibale using ansible-vault
    - passwords.yml

  vars:
    engine_fqdn: omachace-engine-rpm
    engine_user: admin@internal
    engine_cafile: /Users/omachace/Downloads/pki-resource.cer
    qcow_url: http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img
    template_cluster: cl42
    template_name: mytemplate
    template_memory: 1GiB
    template_cpu: 1
    template_disk_size: 1GiB
    template_disk_storage: data

#roles:
#  - ovirt.image-template

  tasks:
    - name: I
      include_role:
        name: ovirt.image-template
